### ISSUE TITLE
A few notes and ideas

### ISSUE THREAD

**Issue by tin2tin** [okuma10/ImportSubtitles#1]
Nice to see you working on this. 

A few notes:
If you want to add an open-filebrowser button next to the path, there is a template for this in the Template menu: operator_file_import.py

After the import I get this error:
`AttributeError: 'Context' object has no attribute 'active_sequence_strip'` - I'm running the add-on in 2.93. But it works in 3.0: https://developer.blender.org/rBSc84d1ad3dbf4551b55f7b2630ef4ba7f6512b775https://developer.blender.org/rBSc84d1ad3dbf4551b55f7b2630ef4ba7f6512b775

For some odd reason can't the font type be batch changed with Copy to Selected, so maybe you can find a way to work around that?

The text strips can actually insert text with forced text breaks, but you just can't insert them manually in the string widget. Adding a string like this "line 1"+chr(13)+"line 2" to the text strip will draw the text in two lines.

**Comment by okuma10** [comment]
Hey thanks for pointing that about the file browser, I looked things up and already added the "import file" button to select the file path.

I have to look it up. But I think the issue with the `active_sequence_strip` is that if you try to change position and the other settings right after import, you have to have a singe line `Sub.`-named sequence selected. When they are created, they are selected, but no sequence is `active` . So you have to deselect and select the singe line sequence.
Which leads me to your suggestion about the multi line subs. The reason I had it that you have to select a single line, was because I wanted to force the user to interact with the single lines rather than the double lines since the double lines are arranged based on the single line. But if there is a way to set a single text string with an escape character of some sorts appear as double or triple line or more, that's even better. you say that you cannot set this in the string input of the sequence? I have to check it out. If so I'll have to rework things a bit.

On the font type , are you saying that copy to selected doesn't work on font change? If so then I'll add it to the loop that checks and applies the changes in position, box margin etc... My idea was to have such main features like color and font be set from the addon as well on `Update` but I figured people can use the `Copy to Selected` , for now. I'll try the things you suggested and if the font is not being updated I'll add the font change to the update function.

**Comment by okuma10** [comment]
Ok checked the things you mentioned, yes there is no 'Copy to Selected' for fonts...I'll add that to the update function, and I'll work on the multiple line text fields using the `\n`.
